### ISSUE TITLE
react-native get started demo didn't work, print ":CFBundleIdentifier", Does Not Exist 

### ISSUE THREAD

**Issue by xhlwill** [xhlwill/blog#6]
I run command 'react-native run-ios' in the latest react-native-cli@1.2.0, but this error keep showing
```
...
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```
the full error log is [**here**](https://gist.github.com/xhlwill/7144dccd98832f20dff1d4c92b100292).

**Comment by xhlwill** [comment]
and error
```
error: use of undeclared identifier 'UIUserInterfaceIdiomCarPlay'; did you mean 'UIUserInterfaceIdiomPad'?
```

**Comment by xhlwill** [comment]
finally I read [this issue](https://github.com/facebook/react-native/issues/7308), and it's solved after I upgraded Xcode from 7.2 to 8.1, curious about why?

**Comment by scurlyhair** [comment]
this issue might be help:
[https://github.com/facebook/react-native/issues/14423](https://github.com/facebook/react-native/issues/14423)

**Comment by phasedarray** [comment]
I found this issue may come out if 8081 port is occupied(In my case it is occupied by McAfee). 
Run command **sudo lsof -i :8081** to check which process has token the 8081 port. 
Or you can run **react-native run-ios --port 8082** to specify another port.
